---
- name: Stop any running zookeeper container
  docker_container:
    name: zookeeper
    state: absent

- name: Start zookeeper container
  docker_container:
    name: zookeeper
    image: wurstmeister/zookeeper:{{ zookeeper_version }}
    state: started
    ports: "2181:{{ zookeeper_port }}"
