---

# From Ansible Galaxy
- src: geerlingguy.docker

- src: geerlingguy.java
  version: "1.7.4"

- src: geerlingguy.jenkins
  version: "2.7.3"

- src: geerlingguy.firewall

- src: geerlingguy.ansible
