---

# From Ansible Galaxy
- src: geerlingguy.docker
  version: "2.1.0"
  name: docker

- src: geerlingguy.java
  version: "1.7.4"
  name: java

- src: geerlingguy.jenkins
  version: "3.1.2"
  name: jenkins

- src: geerlingguy.firewall
  version: "2.3.0"
  name: firewall

- src: geerlingguy.ansible
  version: "1.2.0"
  name: ansible

# Installs the EPEL repository (Extra Packages for Enterprise Linux) for RHEL/CentOS.
- src: geerlingguy.repo-epel
  version: "1.2.3"
  name: centos-epel-repo

# We want ansible to run Docker containers : https://github.com/geerlingguy/ansible-role-pip
- src: geerlingguy.pip
  version: "1.0.0"
  name: pip 
