---

# From Ansible Galaxy
- src: geerlingguy.docker
  # version: "2.7.3"
  name: docker

- src: geerlingguy.java
  version: "1.7.4"
  name: java

- src: geerlingguy.jenkins
  version: "2.7.3"
  name: jenkins

- src: geerlingguy.firewall
  # version: "2.7.3"
  name: firewall

- src: geerlingguy.ansible
  # version: "2.7.3"
  name: ansible
