---
- name: Run Splunk forwarder
  docker_container:
    name: splunk-forwarder
    image: splunk/universalforwarder:6.5.0
    state: started
    ports: "5514:1514/udp"
    env:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ADD: udp 1514
      SPLUNK_FORWARD_SERVER: "192.168.1.10:9997" # User variable for splunk server hostname
      restart: always
      SPLUNK_USER: root
