---
- name: Stop any running splunk-forwarder container
  docker_container:
    name: splunk-forwarder
    state: absent


- name: Start splunk-forwarder 
  docker_container:
    name: splunk-forwarder
    image: splunk/universalforwarder:{{ splunk_forwarder_version }}
    state: started
    ports: 
      - "{{ splunk_forwarder_network_input_port }}:1514/udp"
      - "{{ splunk_forwarder_http_port }}:8088"
      - "{{ splunk_forwarder_service_port }}:8089"
    env:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ADD: 'udp 1514'
      SPLUNK_FORWARD_SERVER: "{{ splunk_forwarder_server_host }}:{{ splunk_forwarder_server_port }}" 
      restart: always
      SPLUNK_USER: root

# See how to configure the forwarder : https://hub.docker.com/r/splunk/universalforwarder/#how-to-use-the-universal-forwarder-docker-image
