---
- name: Stop any running kafka container 
  docker_container:
    name: kafka
    state: absent

- name: Start new kafka container 
  docker_container:
    name: kafka
    image: wurstmeister/kafka:{{ kafka_version }}
    state: started
    ports: "{{ kafka_port }}:9092"
    env:
      KAFKA_ADVERTISED_HOST_NAME: "{{ ansible_eth1.ipv4.address }}"
      # KAFKA_ADVERTISED_HOST_NAME: "{{inventory_hostname}}" 
      KAFKA_ADVERTISED_PORT: "{{ kafka_port }}"
      # KAFKA_CREATE_TOPICS: "test_topic:2:3" # 2 partitions and 3 replicas
      KAFKA_ZOOKEEPER_CONNECT: "{{ zookeeper_host }}:{{ zookeeper_port }}"
