---
- name: Stop any running splunk-server container
  docker_container:
    name: splunk-server
    state: absent

- name: Start splunk-server container
  docker_container:
    name: splunk-server
    image: splunk/splunk:{{ splunk_server_version }}
    state: started
    ports: 
      - "{{ splunk_server_web_port }}:8000" 
      - "{{ splunk_server_network_input_port }}:1514"
      - "{{ splunk_server_service_port }}:8088"
    env:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ADD: tcp 1514
      SPLUNK_USER: root
