---
- name: Run Docker Registry
  docker_container:
    name: registry
    image: registry:2.6.1
    state: started
    ports: "5000:5000"

    ## sudo docker run -d \
    ##     -p 5001:5001 -p 5000:5000 \
    ##     --restart=always \
    ##     --name registry -v /data/registry:/var/lib/registry \
    ##     -v /root/certs:/certs \
    ##     -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
    ##     -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
    ##     -e REGISTRY_HTTP_DEBUG_ADDR=':5001' registry:2.2.1
