---
- name: Run Kafka broker
  docker_container:
    name: kafka
    image: wurstmeister/kafka:0.10.2.0
    state: started
    ports: "9092:9092"
    env:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.1.1" # TODO: Dynamic hostname
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "192.168.1.1:9080"
