---
- name: Configure CI server
  hosts: ci-server
  become: yes
  
  roles:
    - centos-epel-repo
    - ansible
    - jenkins

  tasks:
#    - include: include/ci/jenkins-config.yml
    - include: include/ci/docker-registry.yml
