---
- name: Configure CI server
  hosts: ci-server
  become: yes
  
  #  vars_files: 
  #    - vars/vars.yml
  #    - vars/vault.yml

  roles:
    - ansible
    - jenkins

  tasks:
    - include: include/ci/jenkins-config.yml
    - include: include/ci/docker-registry.yml
