---
- name: Installing and configuring Docker 
  hosts: all
  become: yes
  vars: 
    ### docker-py
    pip_install_packages: 
      - name: docker
        version: "2.5.0"
  roles:
    - role: centos-epel-repo
      when: "ansible_os_family == 'RedHat'"
    - pip
    - { role: docker, tags: ["docker"] }

  tasks:
    - include: include/docker/docker-config.yml
