### JAVA
# java_packages: openjdk-8-jdk when OS is Ubuntu
java_packages: java-1.8.0-openjdk

#######################################################

### JENKINS
jenkins_hostname: jenkins.yakhyadabo.com
jenkins_http_port: 8080
jenkins_version: "2.84"
jenkins_plugins:
  # - ldap
  - git
  - job-dsl
    #  - workflow-aggregator
    #  - build-pipeline-plugin
  - ansicolor
# ldap_port: "389"
# ldap_server: "192.168.1.1"
# ldap_root_dn: "dc=example,dc=com"
# ldap_manager_dn: "cn=admin,dc=example,dc=com"
