---
# https://github.com/geerlingguy/ansible-vagrant-examples/blob/master/docker/provisioning/setup.yml

#- name: Add vagrant user to docker group.
#  user:
#    name: vagrant
#    groups: docker
#    append: yes
#  become: yes
#
- name: Install Pip.
  apt: name=python-pip state=installed
  become: yes

- name: Install Docker Python library
  pip: name=docker-py state=present
