---
- name: Installing and configuring Docker 
  hosts: all
  become: yes
  roles:
    - { role: geerlingguy.docker, tags: ["docker"] }
  tasks:
    - include: ../../include/docker-config.yml


- name: Configure CI server
  hosts: ci-server
  become: yes
  vars:
    - jenkins_hostname: localhost
    - jenkins_http_port: 8083
    - jenkins_version: "2.53"
    - jenkins_plugins:
      - ldap
      - git
      - job-dsl
      - workflow-aggregator
      - build-pipeline-plugin
      - ansicolor
    - firewall_allowed_tcp_ports:
      - "22"
      - "8083"
  roles:
    - geerlingguy.ansible
    - geerlingguy.firewall
    - geerlingguy.jenkins
    #    - git
  tasks:
    - include: jenkins-config.yml
    - include: docker-setup.yml
    - include: docker-registry.yml
