---
- name: Installing and configuring Docker 
  hosts: all
  become: yes
  roles:
    - { role: docker, tags: ["docker"] }

  tasks:
    - include: ../../include/docker-config.yml


- name: Configure CI server
  hosts: ci-server
  become: yes
  pre_tasks: 
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'

  vars:
    - java_packages:
      - openjdk-8-jdk
    - jenkins_hostname: localhost
    - jenkins_http_port: 8083
    - jenkins_version: "2.58"
    - jenkins_package_state: lastest
    - jenkins_plugins:
      - ldap
      - git
      - job-dsl
      - workflow-aggregator
      - build-pipeline-plugin
      - ansicolor
    - ldap_server: "192.168.1.1"
    - ldap_port: "389"
    - ldap_root_dn: "dc=example,dc=com"
    - ldap_manager_dn: "cn=admin,dc=example,dc=com"
    - ldap_manager_password: "toor"

  roles:
    - ansible
    - jenkins

  tasks:
    - include: jenkins-config.yml
    - include: docker-setup.yml
    - include: docker-registry.yml
