---
- name: Installing and configuring Docker 
  hosts: all
  sudo: yes
  roles:
    - { role: geerlingguy.docker, tags: ["docker"] }


- name: Configure CI server
  hosts: ci-server
  vars:
    - jenkins_hostname: localhost
    - jenkins_http_port: 8083
    - jenkins_version: "2.53"
    - jenkins_plugins:
      - ldap
      - git
      - job-dsl
      - workflow-aggregator
      - build-pipeline-plugin
      - ansicolor
    - firewall_allowed_tcp_ports:
      - "22"
      - "8083"
  sudo: yes
  roles:
    - geerlingguy.ansible
    - geerlingguy.firewall
    - geerlingguy.jenkins
    #    - git
  tasks:
   - name: Set /etc/ansible owner to user jenkins
     file: path=/etc/ansible owner=jenkins group=jenkins recurse=yes

