---
- name: Configure CI server
  hosts: ci-server
  vars_files: 
    - vars/vars.yml
    - vars/vault.yml
  become: yes

  pre_tasks: 
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'

  roles:
    - ansible
    - jenkins

  tasks:
    - include: jenkins-config.yml
    - include: docker-setup.yml
    - include: docker-registry.yml
